language: cpp
#dist: bionic
os: linux
compiler: g++

before_install:
  - pushd ${HOME}
  - apt-get update
  - apt-get install
  - wget https://github.com/Kitware/CMake/releases/download/v3.19.1/cmake-3.19.1-Linux-x86_64.tar.gz
  - popd

install:
  - pushd ${HOME}
  - tar -xf cmake-3.19.1-Linux-x86_64.tar.gz
  - export PATH="${PWD}/cmake-3.19.1-Linux-x86_64/bin:${PATH}"
  - sudo apt-get install -qq g++-10
  #- export CXX="g++-9"
  - sudo apt-get install ggcov
  #- sudo apt-get install libxmu-dev libxi-dev
  #- sudo ln -sf /usr/bin/gcov-9 /usr/bin/gcov
  - pip install --user cpp-coveralls
  #- sudo pip install --upgrade ndg-httpsclient
  - popd
script:
  - mkdir _build
  - cd _build
  - cmake ..
  - make
  - ./tests

after_success:
  - coveralls --root ../ --exclude tests/src --exclude app --exclude dependencies -E ".*CMakeFiles.*"


